//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v3_languageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class cIient
    {
        public int IDClient { get; set; }
        public string SecondName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ClientPhoto { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateOfRegistration { get; set; }
        public string column10 { get; set; }
    }
}
