//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v3_languageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.ClientService = new HashSet<ClientService>();
            this.TagOfClient = new HashSet<TagOfClient>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string FEMALE { get; set; }
        public string PATRONYMIC { get; set; }
        public string GENDER { get; set; }
        public double PHONE { get; set; }
        public string PHOTO { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEREGISTRY { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagOfClient> TagOfClient { get; set; }
    }
}
