//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v3_languageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicee
    {
        public string ServiceID { get; set; }
        public string ServiceName { get; set; }
        public int Duration_min { get; set; }
        public int Cost_rub { get; set; }
        public string Discount { get; set; }
    }
}
