//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace v3_languageSchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCIient
    {
        public string ClientID { get; set; }
        public string Client { get; set; }
        public System.DateTime StartService { get; set; }
        public string Вид { get; set; }
        public string IdServer { get; set; }
    }
}
